const arrayData = [
  {
    id: 1,
    category: "Concert",
    title: "Coldplay Live",
    organizer: "Emily Winchester",
    participants: 120,
    date: "15 Apr, 2023",
  },
  {
    id: 2,
    category: "Workshop",
    title: "Coding 101",
    organizer: "David Robinson",
    participants: 50,
    date: "22 Jun, 2023",
  },
  {
    id: 3,
    category: "Meetup",
    title: "Marketing Gurus",
    organizer: "Sarah Lee",
    participants: 200,
    date: "12 Jul, 2023",
  },
  {
    id: 4,
    category: "Conference",
    title: "Tech Summit",
    organizer: "Michael Brown",
    participants: 350,
    date: "20 Aug, 2023",
  },
  {
    id: 5,
    category: "Course",
    title: "Python Programming",
    organizer: "Jessica Taylor",
    participants: 80,
    date: "28 Sep, 2023",
  },
  {
    id: 6,
    category: "Concert",
    title: "Taylor Swift Tour",
    organizer: "James Parker",
    participants: 180,
    date: "10 Oct, 2023",
  },
  {
    id: 7,
    category: "Workshop",
    title: "Data Analysis",
    organizer: "Kevin White",
    participants: 60,
    date: "24 Nov, 2023",
  },
  {
    id: 8,
    category: "Meetup",
    title: "Foodie Friends",
    organizer: "Emily Wilson",
    participants: 220,
    date: "14 Dec, 2023",
  },
  {
    id: 9,
    category: "Conference",
    title: "Design Summit",
    organizer: "Lauren Hall",
    participants: 300,
    date: "15 Jan, 2024",
  },
  {
    id: 10,
    category: "Course",
    title: "Java Development",
    organizer: "Ryan Hernandez",
    participants: 90,
    date: "19 Feb, 2024",
  },
  {
    id: 11,
    category: "Concert",
    title: "AC/DC Rock",
    organizer: "Hannah Reed",
    participants: 140,
    date: "3 Mar, 2024",
  },
  {
    id: 12,
    category: "Workshop",
    title: "Leadership Skills",
    organizer: "Alexandra Perez",
    participants: 70,
    date: "21 Apr, 2024",
  },
  {
    id: 13,
    category: "Meetup",
    title: "Travel Enthusiasts",
    organizer: "Christopher Lewis",
    participants: 250,
    date: "9 Jun, 2024",
  },
  {
    id: 14,
    category: "Conference",
    title: "Business Conference",
    organizer: "Emily Chen",
    participants: 380,
    date: "25 Jul, 2024",
  },
  {
    id: 15,
    category: "Course",
    title: "Machine Learning",
    organizer: "James Martin",
    participants: 100,
    date: "13 Aug, 2024",
  },
  {
    id: 16,
    category: "Concert",
    title: "Kanye West Concert",
    organizer: "Jessica Harris",
    participants: 160,
    date: "2 Sep, 2024",
  },
  {
    id: 17,
    category: "Workshop",
    title: "Creative Writing",
    organizer: "Michael Davis",
    participants: 45,
    date: "16 Oct, 2024",
  },
  {
    id: 18,
    category: "Meetup",
    title: "Sports Fans",
    organizer: "Lauren Smith",
    participants: 210,
    date: "27 Nov, 2024",
  },
  {
    id: 19,
    category: "Conference",
    title: "HR Summit",
    organizer: "Emily Wallace",
    participants: 410,
    date: "11 Dec, 2024",
  },
  {
    id: 20,
    category: "Course",
    title: "Data Science",
    organizer: "Kevin Johnson",
    participants: 85,
    date: "8 Jan, 2025",
  },
  {
    id: 21,
    category: "Concert",
    title: "Lady Gaga Tour",
    organizer: "Sarah Patel",
    participants: 130,
    date: "15 Feb, 2025",
  },
  {
    id: 22,
    category: "Workshop",
    title: "Web Development",
    organizer: "James Brooks",
    participants: 65,
    date: "22 Mar, 2025",
  },
  {
    id: 23,
    category: "Meetup",
    title: "Book Club",
    organizer: "Hannah Adams",
    participants: 190,
    date: "5 Apr, 2025",
  },
  {
    id: 24,
    category: "Conference",
    title: "Gaming Convention",
    organizer: "Lauren Russell",
    participants: 390,
    date: "20 May, 2025",
  },
  {
    id: 25,
    category: "Course",
    title: "Mobile App Development",
    organizer: "Emily Davis",
    participants: 95,
    date: "3 Jun, 2025",
  },
  {
    id: 26,
    category: "Concert",
    title: "The Rolling Stones",
    organizer: "Jessica Nelson",
    participants: 150,
    date: "17 Jul, 2025",
  },
  {
    id: 27,
    category: "Workshop",
    title: "Graphic Design",
    organizer: "Ryan Thompson",
    participants: 55,
    date: "14 Aug, 2025",
  },
  {
    id: 28,
    category: "Meetup",
    title: "Photography Enthusiasts",
    organizer: "Christopher Hall",
    participants: 230,
    date: "28 Sep, 2025",
  },
  {
    id: 29,
    category: "Conference",
    title: "Education Summit",
    organizer: "Hannah Martin",
    participants: 430,
    date: "1 Oct, 2025",
  },
  {
    id: 30,
    category: "Course",
    title: "Certified Financial Planner",
    organizer: "Michael Harris",
    participants: 35,
    date: "8 Oct, 2025 ",
  },
  {
    id: 31,
    category: "Concert",
    title: "Imagine Dragons",
    organizer: "Emily Patel",
    participants: 190,
    date: "22 Oct, 2025",
  },
  {
    id: 32,
    category: "Workshop",
    title: "Public Speaking",
    organizer: "James Miller",
    participants: 50,
    date: "12 Nov, 2025",
  },
  {
    id: 33,
    category: "Meetup",
    title: "Food and Wine",
    organizer: "Lauren Adams",
    participants: 240,
    date: "5 Dec, 2025",
  },
  {
    id: 34,
    category: "Conference",
    title: "Real Estate Conference",
    organizer: "Hannah Smith",
    participants: 480,
    date: "10 Dec, 2025",
  },
  {
    id: 35,
    category: "Course",
    title: "Environmental Science",
    organizer: "Ryan Brooks",
    participants: 75,
    date: "7 Jan, 2026",
  },
  {
    id: 36,
    category: "Concert",
    title: "U2 Concert",
    organizer: "Michael Davis",
    participants: 220,
    date: "14 Feb, 2026",
  },
  {
    id: 37,
    category: "Workshop",
    title: "Digital Marketing",
    organizer: "Emily Wallace",
    participants: 70,
    date: "21 Feb, 2026",
  },
  {
    id: 38,
    category: "Meetup",
    title: "Sports Fanatics",
    organizer: "James Patel",
    participants: 260,
    date: "7 Mar, 2026",
  },
  {
    id: 39,
    category: "Conference",
    title: "Health and Wellness",
    organizer: "Lauren Russell",
    participants: 510,
    date: "21 Mar, 2026",
  },
  {
    id: 40,
    category: "Course",
    title: "Cybersecurity",
    organizer: "Kevin Johnson",
    participants: 105,
    date: "18 Apr, 2026",
  },
];

export default arrayData;
